# backend/app/core/email.py
from fastapi_mail import FastMail, MessageSchema, ConnectionConfig, MessageType
from pydantic import EmailStr
from typing import List
import os

# 📧 Email Configuration
# 📧 邮件配置
# Read from .env securely
# 安全地从环境变量中读取配置
conf = ConnectionConfig(
    MAIL_USERNAME = os.getenv("MAIL_USERNAME"),      
    MAIL_PASSWORD = os.getenv("MAIL_PASSWORD"),      
    MAIL_FROM = os.getenv("MAIL_FROM"),          
    MAIL_PORT = int(os.getenv("MAIL_PORT", 465)),    # Convert to int / 转成整数
    MAIL_SERVER = os.getenv("MAIL_SERVER", "smtp.qq.com"),            
    MAIL_STARTTLS = False, 
    MAIL_SSL_TLS = True,
    USE_CREDENTIALS = True,
    VALIDATE_CERTS = True
)

async def send_absent_notification(email_list: List[str], class_name: str):
    """
    Send absence notification emails
    """
    if not email_list:
        return

    # Professional English Email Template
    # 专业的英文邮件模板
    html = f"""
    <div style="font-family: Arial, sans-serif; color: #333;">
        <h3 style="color: #d9534f;">Attendance Absence Notification</h3>
        <p>Dear Student,</p>
        <p>The system has detected that you have been marked as <strong style="color: #d9534f;">Absent</strong> in the recently concluded attendance check for the <strong>{class_name}</strong> course.</p>
        <p>If you were actually present in the classroom, please contact the instructor after class to correct your attendance record.</p>
        <br>
        <hr style="border: none; border-top: 1px solid #eee;" />
        <p style="font-size: 12px; color: #777;"><em>This email is automatically generated by the Smart Attendance System. Please do not reply.</em></p>
    </div>
    """

    message = MessageSchema(
        subject=f"[Alert] Absence Notification for {class_name}",
        recipients=email_list,
        body=html,
        subtype=MessageType.html
    )

    fm = FastMail(conf)
    try:
        await fm.send_message(message)
        print(f"✅ [Email] Email sent successfully to {len(email_list)} recipient(s)")
    except Exception as e:
        print(f"❌ [Email] Failed to send email: {e}")